[package]
name = "vulkan_tutorial"
version = "0.1.0"
edition = "2021"

[lib]
name = "vulkan_tutorial"
path = "src/lib/mod.rs"

[dependencies]
ash = "0.37.2"
log = "0.4.17"
nalgebra = "0.32.2"
png = "0.17.9"
pretty_env_logger = "0.4.0"
winit = "0.28.4"
